# Generated by Django 3.0.5 on 2022-05-13 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20220513_0603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='address',
            new_name='addresss',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='city',
            new_name='citys',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='date_added',
            new_name='date_addeds',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='state',
            new_name='states',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='zipcode',
            new_name='zipcodes',
        ),
    ]
