# Generated by Django 3.0.5 on 2022-05-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='service',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='ApartmentMeters',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='services',
            name='NumberOfRooms',
            field=models.IntegerField(),
        ),
    ]
