# Generated by Django 3.0.5 on 2022-05-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20220512_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='customer',
        ),
        migrations.AddField(
            model_name='services',
            name='emailAddress',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
