# Generated by Django 3.0.5 on 2022-05-13 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20220513_0621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='addresss',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='citys',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='date_addeds',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='states',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='zipcodes',
            new_name='zipcode',
        ),
    ]
